version: "3.9"

services:
  blockchain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projeto_blockchain
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python /app/app.py
    restart: always
